### ISSUE TITLE
Secondary/Extended bitmap

### ISSUE THREAD

**Issue by NicolasAgra** [manoutoftime/pyiso8583#1]
Hello, is there a way to define field 1 (secondary/extended bitmap) automatically according to the fields? In the same way that primary bitmap is defined. Regards!!

**Comment by manoutoftime** [comment]
Secondary bitmap will be added automatically if there is a 65-128 field defined.

Does that not happen for you?

**Comment by NicolasAgra** [comment]
Nevermind! I just realized I was looking in another place to add field 128, I added to the dictionary and specified to field "bm", and the secondary bitmap was added successfully. Do you know if I can change the format of the bitmap from binary to double hexadecimal symbol? (I was trying to change at the specification dictionary but did not find any correct python encoding)

**Comment by manoutoftime** [comment]
No problem. Documentation can be more clear about relationship of "bm" and "fields".

Do you mean hex char string instead of BCD? If so simply defining as "ascii" will do. For example:

```python
import iso8583
from iso8583.specs import default as spec
doc = {"bm": set([2]), "t": "0200", "2": "1234567"}

# BCD
spec["p"]["data_enc"] = "b"
raw, _ = iso8583.encode(doc, spec)
raw
bytearray(b'0200@\x00\x00\x00\x00\x00\x00\x00071234567')

# Hex char string
spec["p"]["data_enc"] = "ascii"
raw, _ = iso8583.encode(doc, spec)
raw
bytearray(b'02004000000000000000071234567')

# Hex char string
spec["p"]["data_enc"] = "latin-1"
raw, _ = iso8583.encode(doc, spec)
raw
bytearray(b'02004000000000000000071234567')
```

**Comment by NicolasAgra** [comment]
Excellent, second case it is, I think it was another special encoding but I made the manual conversion to check and it is correct!. Regards!
