### ISSUE TITLE
Install is not working

### ISSUE THREAD

**Issue by flukedf** [manoutoftime/pyiso8583#2]
Hello,

I try to install pyiso8583 with pip install but not working, Can you help me with this wrong?
I attached a picture from error.
Thanks a lot

![image](https://user-images.githubusercontent.com/7216451/84531652-88eef180-acaa-11ea-8e17-b2c17f02bfc9.png)

**Comment by manoutoftime** [comment]
I'm not sure what to say aside from it's definitely available on pypi index.

![image](https://user-images.githubusercontent.com/447868/84534958-dd996900-acb8-11ea-85a9-1e4017372530.png)

Do you know if you use Python 2 or 3? The package is available for 3 only. Could this be the problem?

**Comment by manoutoftime** [comment]
I’m going to close this. If there’s something wrong with the package, please let me know.
